name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: |
          npm ci
          npm run build
      - name: Run nodes
        env:
          RPC: http://localhost:8545
        run: |
          ./bin/revive-dev-node --dev & ./bin/eth-rpc --dev &

          sleep 10

          npm run estimate
