name: "Validate the issue description and prepare the transaction"
on:
  issues:
    types: [opened, edited]
env:
  ISSUE_BODY: ${{ github.event.issue.body }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NUMBER: ${{ github.event.issue.number }}
  REPO: ${{ github.repository }}

jobs:
  prepareTransaction:
    if: ${{ contains(github.event.issue.labels.*.name, 'new-chain') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run the validation script
        run: |
          npm ci
          RPC_URL=$(echo "$ISSUE_BODY" | grep -E -o 'https?://[^ ]+' -m 1 | head -1)
          SUMMARY_FILE=summary.json RPC=$RPC_URL npm run verify:new-chain-request || true
          echo "COMMENT_OUTPUT=$(jq -r '.commentOutput' summary.json)" >> $GITHUB_ENV
          echo "LABEL_OPERATION=$(jq -r '.labelOperation' summary.json)" >> $GITHUB_ENV
        env:
          ISSUE_BODY: ${{ env.ISSUE_BODY }}
          FACTORY_ADDRESS: ${{ env.FACTORY_ADDRESS }}
          FACTORY_BYTECODE: ${{ env.FACTORY_BYTECODE }}
          FACTORY_DEPLOYER_ADDRESS: ${{ env.FACTORY_DEPLOYER_ADDRESS }}

      - name: Post Comment to the Issue
        if: always()
        env:
          COMMENT_OUTPUT: ${{ env.COMMENT_OUTPUT }}
        run: |
          gh issue comment "$NUMBER" --repo "$REPO" --body "$COMMENT_OUTPUT" --edit-last || gh issue comment "$NUMBER" --repo "$REPO" --body "$COMMENT_OUTPUT"
          gh issue edit "$NUMBER" --repo "$REPO" "$LABEL_OPERATION" ready-to-deploy

  # Workflows where all jobs are skipped are counted as "failed". In order to
  # work around this, always execute a dummy job regardless of whether or not
  # the `new-chain` tag is set.
  alwaysExecuted:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "always executed"
